export const storeProducts = [
  {
    id: 1,
    title: "Cheese Curry",
    img: "img/product-1.png",
    price: 3,
    company: "Nissin",
    info: "Cheese Curry Favor Cup Noodle",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Cup Noodle",
    img: "img/product-2.png",
    price: 2,
    company: "Nissin",
    info: "Convinent Cup Noodle",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Hong Kong Style Noodle",
    img: "img/product-3.png",
    price: 4,
    company: "Nissin",
    info: "Hong Kong Style Instant Noodle",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "UFO",
    img: "img/product-4.png",
    price: 4,
    company: "Nissin",
    info: "Dry Noodle",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Mac and Cheese",
    img: "img/product-5.png",
    price: 4,
    company: "Unknown",
    info: "Mac and Cheese Spaghetti",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Big Bowl",
    img: "img/product-6.png",
    price: 7,
    company: "SamYang",
    info: "Big Portion of Noodle",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Udon",
    img: "img/product-7.png",
    price: 7,
    company: "Nongshim",
    info: "Home Style Udon",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Crab Favor Udon",
    img: "img/product-8.png",
    price: 2,
    company: "Nissin",
    info: "Crab Favor Udon",
    inCart: false,
    count: 0,
    total: 0,
  },
]

export const detailProduct = {
  id: 1,
  title: "Cheese Curry",
  img: "img/product-1.png",
  price: 3,
  company: "Nissin",
  info: "Cheese Curry Favor Cup Noodle",
  inCart: false,
  count: 0,
  total: 0,
}

// import React, { connect } from "react"
// function mapStateToProps(state) {
//   return { coffeeItems: state.coffeeItems }
// }

// const storeProducts = this.props.coffeeItems.map(({ node }) => ({
//   id: node.id,
//   img: "",
//   title: node.title,
//   price: node.price,
//   description: node.description.description,
//   id: 3,
//   company: "Nissin",
//   info: "Hong Kong Style Instant Noodle",
//   inCart: false,
//   count: 0,
//   total: 0,
// }))

// export default connect(mapStateToProps)(storeProducts)
